spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/seguridad}
    username: ${DATABASE_USERNAME:seguridad}
    password: ${DATABASE_PASSWORD:seguridad}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
